# https://github.com/aquasecurity/trivy-action
name: "Trivy"
description: "Vurnerability Scanning"

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        ignore-unfixed: true
        format: 'table'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
