name: "Assign"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false

concurrency:
  # Here we use the repository name to avoid conflicts with other repositories
  # Target repositories should use only `${{ github.workflow_ref }}_${{ github.ref }}`
  group: ${{ github.workflow_ref }}_${{ github.ref }}_${{ github.repository }}

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    name: "Label"
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - uses: actions/labeler@v5
