name: "Verify"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      GH_APP_ID:
        type: string
      GH_APP_INSTALLATION_ID:
        type: string
      TF_INPUT:
        type: string
      TF_IN_AUTOMATION:
        type: string
    secrets:
      GH_APP_PEM_FILE:
      TF_TOKEN_APP_TERRAFORM_IO:
      TFE_TOKEN:

concurrency:
  # Here we use the repository name to avoid conflicts with other repositories
  # Target repositories should use only `verify_${{ github.ref }}`
  group: verify_${{ github.ref }}_${{ github.workflow }}_${{ github.repository }}
  cancel-in-progress: true

env:
  # GH
  GITHUB_APP_ID: ${{ vars.GH_APP_ID || inputs.GH_APP_ID }}
  GITHUB_APP_INSTALLATION_ID: ${{ vars.GH_APP_INSTALLATION_ID || inputs.GH_APP_INSTALLATION_ID }}
  GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
  # TF
  TF_INPUT: ${{ vars.TF_INPUT || inputs.TF_INPUT }}
  TF_IN_AUTOMATION: ${{ vars.TF_IN_AUTOMATION || inputs.TF_IN_AUTOMATION }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  # Trivy
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2

defaults:
  run:
    shell: bash

jobs:
  secrets:
    name: "Secrets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/trufflehog
        if: github.repository == 'Inetum-Poland/.github'
      - uses: Inetum-Poland/.github/.github/actions/trufflehog@main
        if: github.repository != 'Inetum-Poland/.github'

  vulnerabilites:
    name: "Vulnerabilites"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/trivy
        if: github.repository == 'Inetum-Poland/.github'
      - uses: Inetum-Poland/.github/.github/actions/trivy@main
        if: github.repository != 'Inetum-Poland/.github'

  pre_commit:
    name: "Pre-Commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/mise
        if: github.repository == 'Inetum-Poland/.github'
      - uses: Inetum-Poland/.github/.github/actions/mise@main
        if: github.repository != 'Inetum-Poland/.github'

      - uses: ./.github/actions/pre_commit
        if: github.repository == 'Inetum-Poland/.github'
      - uses: Inetum-Poland/.github/.github/actions/pre_commit@main
        if: github.repository != 'Inetum-Poland/.github'
